# Generated by Django 4.2 on 2023-06-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("ShortName", models.CharField(max_length=200)),
                ("Currency", models.CharField(max_length=50)),
                ("LongName", models.CharField(max_length=200)),
                ("WHTRate", models.FloatField()),
                ("OrdSeqNo", models.IntegerField()),
                ("Alias1", models.CharField(blank=True, max_length=200, null=True)),
                ("Alias2", models.CharField(blank=True, max_length=200, null=True)),
                ("Adjective1", models.CharField(blank=True, max_length=200, null=True)),
                ("Adjective2", models.CharField(blank=True, max_length=200, null=True)),
                ("Adjective3", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "ID",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("CountryID", models.IntegerField(db_column="CountryID")),
                (
                    "ReportType",
                    models.CharField(db_column="ReportType", max_length=200),
                ),
                ("FinYearEnd", models.DateField(db_column="FinYearEnd")),
                (
                    "CompanyName",
                    models.CharField(db_column="CompanyName", max_length=200),
                ),
                (
                    "DisplayName",
                    models.CharField(db_column="DisplayName", max_length=200),
                ),
                ("SEDOL", models.CharField(db_column="SEDOL", max_length=200)),
                ("ISIN", models.CharField(db_column="ISIN", max_length=200)),
                ("FTTicker", models.CharField(db_column="FTTicker", max_length=200)),
                ("YFTicker", models.CharField(db_column="YFTicker", max_length=200)),
                ("GFTicker", models.CharField(db_column="GFTicker", max_length=200)),
                ("BBTicker", models.CharField(db_column="BBTicker", max_length=200)),
                ("BCTicker", models.CharField(db_column="BCTicker", max_length=200)),
                ("StockDescription", models.TextField(db_column="StockDescription")),
                ("SPCurry", models.CharField(db_column="SPCurry", max_length=200)),
                ("RefCurry", models.CharField(db_column="RefCurry", max_length=200)),
                (
                    "HighValue12mth",
                    models.DecimalField(
                        db_column="12mthHighValue", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "LowValue12mth",
                    models.DecimalField(
                        db_column="12mthLowValue", decimal_places=4, max_digits=19
                    ),
                ),
                ("CurrentSharesOS", models.IntegerField(db_column="CurrentSharesOS")),
                (
                    "CurrentValue",
                    models.DecimalField(
                        db_column="CurrentValue", decimal_places=4, max_digits=19
                    ),
                ),
                ("CurrentDate", models.DateField(db_column="CurrentDate")),
                (
                    "MktCap",
                    models.DecimalField(
                        db_column="MktCap", decimal_places=4, max_digits=19
                    ),
                ),
                ("StockType", models.CharField(db_column="StockType", max_length=200)),
                ("IndexID", models.IntegerField(db_column="IndexID")),
                ("ISIN2", models.CharField(db_column="ISIN2", max_length=200)),
                ("StockURL", models.URLField(db_column="StockURL")),
                ("slug", models.SlugField(blank=True, db_column="slug")),
            ],
            options={
                "db_table": "stock",
                "managed": False,
            },
        ),
    ]
