# Generated by Django 4.2.2 on 2023-06-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinData",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("OrdSeqNo", models.IntegerField()),
                ("FinDataName", models.CharField(max_length=255)),
                ("FinDataType", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CoFinExport",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("FinPerTypeID", models.IntegerField()),
                ("PeriodEnd", models.DateField()),
                ("RepCurry", models.CharField(max_length=255)),
                ("RefCurry", models.CharField(max_length=255)),
                ("RepDate", models.DateField()),
                ("Multiplier", models.CharField(max_length=255)),
                ("RepValue", models.FloatField()),
                ("RefValue", models.FloatField()),
                ("DataSource", models.CharField(max_length=255)),
                ("Reliability", models.IntegerField()),
                ("comment", models.TextField()),
                (
                    "FinDataID",
                    models.ForeignKey(
                        db_column="FinDataID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.findata",
                    ),
                ),
                (
                    "StockID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.stock"
                    ),
                ),
            ],
        ),
    ]
