# Generated by Django 4.2.2 on 2023-06-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_findata_cofinexport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cofinexport",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="findata",
            options={"managed": False},
        ),
    ]
